#!/usr/bin/env nbb
;; scripts/emit_coverage_plan.cljs — derive the jurisdiction universe and
;; project the current coverage plan into data/.
;;
;;   nbb --classpath src scripts/emit_coverage_plan.cljs [<cloud-itonami-dir>]
;;
;; The universe is NOT hand-typed here. It is derived from the existing
;; `cloud-itonami-iso3166-*` family (225 repositories), which is this
;; workspace's already-established list of jurisdictions. Codes containing a
;; hyphen (JPN-FSA, USA-SEC, CHN-ADVERTISING, ...) are that family's
;; agency/sub-national entries, not jurisdictions, and are excluded -- with
;; the excluded set written out so the filter can be audited rather than
;; trusted.
;;
;; If the family directory is not present (a sparse checkout), the previously
;; generated universe file is kept and the script says so instead of silently
;; emitting a smaller world.

(ns emit-coverage-plan
  (:require [clojure.string :as str]
            [clojure.edn :as edn]
            [mortgage.facts :as facts]
            [mortgage.plan :as plan]
            ["fs" :as fs]
            ["path" :as path]))

;; process.argv interleaves nbb's own flags, so locate this script and take
;; whatever follows it rather than trusting a fixed index.
(def family-dir
  (let [argv (js->clj (.-argv js/process))
        i (first (keep-indexed #(when (str/ends-with? %2 "emit_coverage_plan.cljs") %1) argv))]
    (or (when i (nth argv (inc i) nil))
        (path/join (js/process.cwd) ".."))))

(def universe-file "data/jurisdiction-universe.edn")

(defn scan-family []
  (when (fs/existsSync family-dir)
    (->> (js->clj (fs/readdirSync family-dir))
         (keep #(second (re-matches #"cloud-itonami-iso3166-(.+)" %)))
         (map str/upper-case)
         sort
         vec)))

(def scanned (scan-family))
(def sovereign (vec (remove #(str/includes? % "-") scanned)))
(def excluded (vec (filter #(str/includes? % "-") scanned)))

(def universe
  (cond
    (seq sovereign) sovereign
    (fs/existsSync universe-file) (:jurisdictions (edn/read-string (fs/readFileSync universe-file "utf8")))
    :else nil))

(when-not universe
  (println "ERROR: could not scan" family-dir "and no previous" universe-file)
  (set! (.-exitCode js/process) 1))

(when universe
  (when (seq sovereign)
    (fs/writeFileSync
     universe-file
     (str ";; data/jurisdiction-universe.edn — GENERATED by\n"
          ";; scripts/emit_coverage_plan.cljs. Do not hand-edit.\n"
          ";;\n"
          ";; Derived from the cloud-itonami-iso3166-* family in this org (the\n"
          ";; workspace's established jurisdiction list), NOT from a list typed\n"
          ";; here. " (count scanned) " repositories scanned, " (count sovereign)
          " jurisdictions kept,\n"
          ";; " (count excluded) " agency/sub-national codes excluded -- the excluded set is\n"
          ";; written out below so the filter can be audited.\n\n"
          (with-out-str
            (pr {:scanned (count scanned)
                 :jurisdictions universe
                 :excluded-agency-or-subnational excluded
                 :source "orgs/cloud-itonami/cloud-itonami-iso3166-*"
                 :note "This is the family's coverage, which is not identical to the set of UN member states. It is used because it is the list this workspace already reasons about; a jurisdiction absent here is not a jurisdiction that does not exist."}))
          "\n")))

  (let [prog (plan/progress universe)
        q (plan/queue universe)]
    (fs/writeFileSync
     "data/coverage-plan.edn"
     (str ";; data/coverage-plan.edn — GENERATED by scripts/emit_coverage_plan.cljs.\n"
          ";; Do not hand-edit: this is a SNAPSHOT of computed status, not a\n"
          ";; place to record intent. Intent lives in src/mortgage/plan.cljc.\n"
          ";;\n"
          ";; Every status here is computed from the presence of evidence in\n"
          ";; mortgage.facts/catalog -- no jurisdiction can be marked done.\n\n"
          (with-out-str
            (pr {:generated-from "mortgage.facts/catalog + mortgage.plan/waves"
                 :universe (count universe)
                 :progress prog
                 :queue-size (count q)
                 :next-batch (plan/next-batch universe 12)
                 :waves (mapv #(select-keys % [:wave :name :done :target]) plan/waves)
                 :open-decisions (mapv :id plan/open-decisions)}))
          "\n"))

    (println "universe        :" (count universe) "jurisdictions"
             (str "(" (count excluded) " agency/sub-national codes excluded)"))
    (println "catalog seeded  :" (count facts/catalog))
    (doseq [p plan/planes]
      (println (str "  " (name p) (apply str (repeat (- 16 (count (name p))) " "))
                    ":" (pr-str (get prog p)))))
    (println "queue           :" (count q) "jurisdictions have outstanding work")
    (println "wrote data/coverage-plan.edn" (when (seq sovereign) (str "and " universe-file)))))
